export const IMAGES = {
    'open_video_thumb': require('../assets/images/thumbs/OpenVideo.png'),
    'dmv_driving_thumb': require('../assets/images/thumbs/dmv_driving_thumb.png'),
    'canada_citizen_thumb': require('../assets/images/thumbs/canada-test.png'),
    'turn_off_tv_thumb': require('../assets/images/thumbs/turn_off_tv1.png'),
    'family_channels_thumb': require('../assets/images/pic05.jpg'),
    'catch_them_thumb': require('../assets/images/thumbs/CatchThem2.png'),
    'weDesign': require('../assets/images/we-design.png'),
    'weDevelop': require('../assets/images/we-develop.png'),
    'weDeliver': require('../assets/images/we-deliver.png'),
    'family_channels_thumb': require('../assets/images/thumbs/family_channels_thumb.png'),
    'catch_them_icon': require('../assets/images/icons/catch-them.png'),
    'dmv_driving_icon': require('../assets/images/icons/dmv_driving.png'),
    'canada_citizen_icon': require('../assets/images/icons/canada_citizen_icon.png'),
    'us_citizen_icon': require('../assets/images/icons/us_citizen_icon.png'),
    'uk_citizen_icon': require('../assets/images/icons/uk_citizen_icon.png'),
    'australia_citizen_icon': require('../assets/images/icons/australia_citizen_icon.png'),
    'turn_off_tv_icon': require('../assets/images/icons/turn_off_tv_icon.png'),
}