export const IMAGES = {
  'nfb_film_app_thumb': require('../assets/images/thumbs/NFB_thumb.png'),
  'open_video_thumb': require('../assets/images/thumbs/OpenVideo.png'),
  'dmv_driving_thumb': require('../assets/images/thumbs/dmv_driving_thumb.png'),
  'canada_citizen_thumb': require('../assets/images/thumbs/canada-test.png'),
  'turn_off_tv_thumb': require('../assets/images/thumbs/turn_off_tv1.png'),
  'catch_them_thumb': require('../assets/images/thumbs/CatchThem2.png'),
  'weDesign': require('../assets/images/we-design.png'),
  'weDevelop': require('../assets/images/we-develop.png'),
  'weDeliver': require('../assets/images/we-deliver.png'),
  'family_channels_thumb': require('../assets/images/thumbs/family_channels_thumb.png'),
  'catch_them_icon': require('../assets/images/icons/catch-them.png'),
  'dmv_driving_icon': require('../assets/images/icons/dmv_driving.png'),
  'canadian_driving_icon': require('../assets/images/icons/canadian_driving_icon.png'),
  'canada_citizen_icon': require('../assets/images/icons/canada_citizen_icon.png'),
  'us_citizen_icon': require('../assets/images/icons/us_citizen_icon.png'),
  'uk_citizen_icon': require('../assets/images/icons/uk_citizen_icon.png'),
  'australia_citizen_icon': require('../assets/images/icons/australia_citizen_icon.png'),
  'turn_off_tv_icon': require('../assets/images/icons/turn_off_tv_icon.png'),
  'novie_icon': require('../assets/images/icons/novie_icon.png'),
  'novie_full': require('../assets/images/fulls/Novie/app_feature_graphic_1024x500.png'),
  'novie_thumb': require('../assets/images/thumbs/novie_thumb_539.png'),
  'novie_thumb_2': require('../assets/images/thumbs/novie_thumb_2_539.jpg'),
  'reddu_icon': require('../assets/images/icons/reddu_icon.png'),
  'decal_hoang_oanh': require('../assets/images/thumbs/decalHoangOanh.png'),
  'top_best_youtube_channels_icon': require('../assets/images/icons/topBestYoutubeChannels.png')
}